config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :books, only: [:new,:create, :index, :show, :edit, :update, :destroy]
  resources :users, only:[:index, :show, :edit, :update]
  get "/home/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
   has_one_attached :image
   belongs_to :user
   validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_one_attached :profile_image
 validates :name,presence:true,uniqueness:true,length:{minimum:2, maximum:20}
  validates :introduction,length:{maximum:50}
   def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
     profile_image.variant(resize_to_limit: [width, height]).processed
   end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)

  end



  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book= Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id= current_user.id

   if @book.save
       flash[:notice] = "You have created book successfully."
    redirect_to book_path(@book.id)
   else
     @books = Book.all
     @user = current_user
     render :index
   end

  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user= @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])

   unless @book.user.id == current_user.id
    redirect_to books_path
   end

  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end

  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

   private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    user = User.find(params[:id])

    unless user.id == current_user.id
      redirect_to users_path
    end

  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user= current_user
    @book= Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user =User.find(params[:id])

   unless @user == current_user
    redirect_to user_path(current_user.id)
   end

  end

  def update
      @user = User.find(params[:id])

   unless @user.id == current_user.id
    redirect_to books_path
   end

   if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
   else
      render :edit
   end

  end

private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user = User.find(params[:id])

    unless user.id == current_user.id
      redirect_to books_path
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
<table class= "table">
  <%= image_tag user.get_profile_image(100,100) %>
   <tr>
   <th>name</th>
   <th><%= user.name %></th>
   </tr>
   <tr>
   <th>introduction</th>
   <th><%= user.introduction %></th>
   </tr>
 </table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h1>Editing Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>

 <%= f.submit 'Update Book', class:"btn btn-success" %>

<% end %>
<%= link_to "Show" ,book_path %>
|
<%= link_to "Back" ,books_path %>
</div>
  </div>
   </div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class='container px-5 px-sm-0'>
<div class='row'>
<div class='col-md-3'>

<%= render 'users/list', user: @user %>
<%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit_user_#{@user.id}" do %>
 <i class="fas fa-user-cog"></i>
<% end %>

<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>
<%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>
</div>

<div class='col-md-8 offset-md-1'>
<h2>Books</h2>
<table class='table table-hover table-inverse'>
  <thead>
   <tr>
    <th></th>
    <th>Title</th>
    <th>Opinion</th>
    <th colspan="3"></th>
   </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
    <tr>
       <td>
         <%= link_to user_path(book.user.id) do %>
         <%= image_tag book.user.get_profile_image(80, 80) %>
         <% end %>
       </td>
       <td><%= link_to book.title, book_path(book.id) %></td>
     <td><%= book.body %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>

app/views/books/new.html.erb
<div class='container px-5 px-sm-0'>
<div class='row'>
<div class='col-md-3'>

<%= render 'users/list', user: @user %>

<%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit_user_#{@user.id}" do %>
 <i class="fas fa-user-cog"></i>
<% end %>

<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>
<%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>
</div>

<h2>Books</h2>
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
    <th>Title</th>
    <td><%= image_tag user.get_profile_image(100, 100) %></td>
    <td><%= link_to @book.title, book_path(@book.id) %></td>
    <th>Opinion</th>
    <td><%= @book.body %></td>
    </tr>
  </thead>
  </tbody>
</table>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
  <div class='col-md-3'>

<%= render 'users/list', user: @user %>

<%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit_user_#{@user.id}" do %>
 <i class="fas fa-user-cog"></i>
<% end %>

 <h2>New book</h2>
 <% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book_new, url: '/books', method: :post do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>
<%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>
  </div>

<div class='col-md-8 offset-md-1'>

<h2>Book detail</h2>
<table class='table'>
<tr>
 <td>
 <%= link_to(@book.user) do %>
 <%= image_tag @book.user.get_profile_image(100, 100) %><br>
 <%= @book.user.name %>
 <% end %>
 </td>
 <td><%= link_to @book.title, book_path(@book.id) %></td>
 <td><%= @book.body %></td>
  <% if @book.user == current_user %>
 <td><%= link_to "Edit" , edit_book_path(@book.id), class:"btn btn-success" %></td>
 <td>
  <%= link_to "Destroy", book_path(@book.id), method: :delete, data:{confirm: '本当に削除しますか？'}, class: "btn btn-sm btn-danger" %>
 </td>
 <% end %>
</tr>
</table>

</div>
  </div>
  </div>

app/views/homes/about.html.erb
 <div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
<h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fa-solid fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class:"btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
   </div>

app/views/layouts/application.html.erb
<head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/96de0f4082.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <header>

   <% if user_signed_in? %>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
    <%= link_to "Bookers", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
     <ul class="navbar-nav ml-auto">
      <li>
        <%= link_to user_path(current_user.id), class: "nav-link text-light" do %>
       <i class="fa-solid fa-home"></i> Home
        <% end %>
      </li>

      <li>
        <%= link_to users_path, class: "nav-link text-light" do %>
        <i class="fa-solid fa-users"></i> Users
        <% end %>
      </li>

      <li>
        <%= link_to books_path, class: "nav-link text-light" do %>
        <i class="fa-solid fa-book-open"></i> Books
        <% end %>
      </li>

      <li>
        <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
        <i class="fas fa-sign-out-alt"></i> Log out
        <% end %>
      </li>
    </ul>
   </div>
   </div>
   </nav>

   <% else %>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
    <%= link_to "Bookers", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">

          <li>
            <%= link_to root_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-home"></i> Home
           <% end %>      </li>

          <li>
            <%= link_to about_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-link"></i> About
            <% end %>
          </li>

          <li>
            <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-user-plus"></i> Sign up
            <% end %>
            </li>

          <li>
            <%= link_to new_user_session_path, class: "nav-link text-light" do %>
              <i class="fa-solid fa-sign-in-alt"></i> Log in
             <% end %>
          </li>

        </ul>
      </div>
    </div>
  </nav>

   <% end %>

</header>

<main>

   <% flash.each do |message_type, message| %>
    <div class="flash-message <%= message_type %>"><%= message %>
    </div>

   <% end %>

<%= yield %>

</main>

<footer>

  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>

</footer>

</body>

app/views/users/_list.html.erb
 <h2>User info</h2>
<table class= "table">
  <%= image_tag user.get_profile_image(100,100) %>
   <tr>
   <th>name</th>
   <th><%= user.name %></th>
   </tr>
   <tr>
   <th>introduction</th>
   <th><%= user.introduction %></th>
   </tr>
 </table>

app/views/users/edit.html.erb
<div class='container'>
<div class='row'>
 <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

 <h2>User info</h2>
 <% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= form_with model: @user, url: user_path(@user.id) do |f| %>

 <p>Name</p>
  <%= f.text_field :name %>

 <p>Image</p>
  <%= f.file_field :profile_image, accept: "image/*" %>

　<p>Introduction</p>
  <%= f.text_area :introduction %>

  <%= f.submit 'Update User', class:"btn btn-secondary" %>

  <% end %>

</div>
</div>
 </div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
   <div class='row'>
<div class='col-md-3'>

<%= render 'list', user: @user %>

<%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit_user_#{@user.id}" do %>
 <i class="fas fa-user-cog"></i>
<% end %>

<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>
<%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>
</div>

<div class='col-md-8 offset-md-1'>
<h2>Users</h2>
<table class= "table">
  <tbody>
    <thead>
    <tr>
    <th>image </th>
    <th>name</th>
    <th></th>
    </tr>
    </thead>
<% @users.each do |user| %>
   <tr>
     <td><%= image_tag user.get_profile_image(80, 80) %></td>
     <td><%= user.name %></td>
     <td><%= user.introduction %></td>
    <td><%= link_to "Show" ,user_path(user.id)  %></td>
    </tr>
<% end %>
    </tbody>
    </table>
</div>
   </div>
   </div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
 <div class='row'>
   <div class='col-md-3'>


<%= render 'list', user: @user %>

<%= link_to edit_user_path(@user), class: "btn btn-outline-secondary btn-block edit_user_#{@user.id}" do %>
 <i class="fas fa-user-cog"></i>
<% end %>

<h2>New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <p>Title</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>
<%= f.submit 'Create Book', class:"btn btn-success" %>
<% end %>
  </div>

  <div class='col-md-8 offset-md-1'>
  <h2>Books</h2>
  <table class='table table-hover table-inverse'>
  <thead>
  <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
  <tr>
  <td>
     <%= link_to user_path(book.user.id) do %>
         <%= image_tag book.user.get_profile_image(80, 80) %>
         <% end %>
  </td>
   <td><%= link_to book.title, book_path(book.id) %></td>
    <td><%= book.body %></td>
</tr>
  <% end %>
  </tbody>
  </table>
</div>
</div>
</div>